### ISSUE TITLE
Remove date manipulation from readme

### ISSUE THREAD

**Issue by Daniel15** [ollomagi/react-omni-counter#1]
Things like this:
```
const tomorrow = new Date(Date.now() + 86400000) 
```

Are not a best practice, as this won't work properly across DST transitions (it'll be one hour wrong). It's a bit more verbose, but you're likely looking for something like this:
```
const today = new Date();
const tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, today.getHours(), today.getMinutes(), today.getSeconds())
```
Unfortunately JS doesn't have a good built-in date library yet :/

**Comment by ollomagi** [comment]
Thanks @Daniel15 for pointing this out. Updated with a less verbose version of the code
```
let tomorrow = new Date()
tomorrow.setDate(tomorrow.getDate() + 1)
```
